### ISSUE TITLE
Support boolean TRUE / FALSE literal values

### ISSUE THREAD

**Issue by cben** [yaacov/tree-search-language#10]
Parsing e.g. `managed = FALSE` fails.  Indeed the grammar doesn't have boolean literals:
https://github.com/yaacov/tree-search-language/blob/b3a2bd7a1518111c50fd7235d153c52285e2d113/TSL.g4#L42-L45

Using `managed = 0`, `managed != 1` instead seems to work (using SQL walker, in backend for cloud.redhat.com/openshift).
But this is not what user expects for a boolean field.

**Comment by cben** [comment]
I can work on this unless you beat me to it.

**Comment by yaacov** [comment]
> I can work on this unless you beat me to it.

I do not think I will beat you to it :-)

p.s.
we have a workaround using strings e.g. 'false' and 'true' see:
https://github.com/yaacov/tree-search-language/blob/36e7e9f7edc10fbdc961a870e13b8cb5d800703e/pkg/walkers/semantics/walk.go#L137

**Comment by yaacov** [comment]
p.p.s
using strings to represent boolean is not that uncommon:
http://www.postgresqltutorial.com/postgresql-boolean/

**Comment by cben** [comment]
Thanks. That workaround is in Semantics walker; doesn't work with SQL walker – `managed = 'false'` doesn't match anything.

**Comment by yaacov** [comment]
fixed by https://github.com/yaacov/tree-search-language/pull/21
